#!/bin/bash

command lolcommits || exit 0;

### lolcommits hook (begin) ###
LANG="" && if [ ! -d "$GIT_DIR/rebase-merge" ] && [ "$LOLCOMMITS_CAPTURE_DISABLED" != "true" ]; then lolcommits --capture --delay 0 --animate 1 --fork; fi
###  lolcommits hook (end)  ###
