#!/bin/bash

command lolcommits 2>&1 >/dev/null || exit 0;

### lolcommits hook (begin) ###
GIT_DIR=${GIT_DIR-$(git rev-parse --git-dir)} && LANG="" && if [ ! -d "$GIT_DIR/rebase-merge" ] && [ "$LOLCOMMITS_CAPTURE_DISABLED" != "true" ]; then lolcommits --capture --delay 0 --animate 1 --fork; fi
###  lolcommits hook (end)  ###
