#!/usr/bin/env bash

unamestr=$(uname)

# Files (not deleted) in the index
files=$(git diff-index --name-status --cached HEAD | grep -v "^D" | cut -c3-)
echo -e "\e[1;30mChecking and fixing files with trailing spaces and missing newlines on file endings...\e[0m"
if [ "$files" != "" ]
then
  for f in $files
  do
    # Only examine known text files
    if [[ "$f" =~ [.](json|properties|conf|txt|xml|yml|yaml|md|sh|sql|java|scala|feature)$ ]]
    then

      # Remove trailing whitespace if it exists
      if [[ $unamestr == 'Darwin' ]]; then
        #specific case for Mac OSX
        sed -i '' -e's/[[:space:]]*$//' "$f"
      else
        sed -i 's/[[:space:]]*$//' "$f"
      fi

      # Strip empty lines before and after, leaving ending newline
      [[ $(<$f) =~ ^$'\n'*(.*)$ ]] && echo "${BASH_REMATCH[1]}" > "$f"

      git add "$f"
    fi
  done
fi

my_dir="$(dirname "$0")"

#"$my_dir/hook.sh $@"
