#!/usr/bin/env bash

COMMIT_EDITMSG=$1

addBranchName() {
  branch_name=$(git symbolic-ref --short -q HEAD)
  branch_name=${branch_name##refs/heads/}
  NAME=${branch_name:-HEAD}
  NAME=$(echo $NAME | grep -o -i "\(\w\+\-\d\+\|SPIKE\|HOTFIX\)")
  #NAME=$(git branch | grep '*' | sed 's/* //')
  DESCRIPTION=$(git config branch."$NAME".description)
  echo "[$NAME]: $(cat $COMMIT_EDITMSG)" > $COMMIT_EDITMSG
  if [ -n "$DESCRIPTION" ]
  then
     echo "" >> $COMMIT_EDITMSG
     echo $DESCRIPTION >> $COMMIT_EDITMSG
  fi
}

MERGE=$(cat $COMMIT_EDITMSG|grep 'Merge (branch|pull request|maven-release-plugin)'|wc -l)

if [ -z "$firstLine" ] ; then
  if [ $MERGE -eq 0 ] ; then
    addBranchName
  fi
fi
