#!/opt/homebrew/bin/bash

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

# Alpha 0.9 = Hex D2
# Alpha 0.8 = Hex A4

sketchybar --bar       \
    height=30          \
    blur_radius=0      \
    position=top       \
    sticky=on          \
    padding_left=2     \
    padding_right=2    \
    font_smoothing=yes \
    color=0x00FFFFFF

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default                  \
    updates=when_shown                \
    drawing=on                        \
                                      \
    y_offset=-2                       \
                                      \
    label.color=0xFFFFFFFF            \
    label.highlight_color=0xFF363a4f  \
    label.font="IosevkaTerm Nerd Font Mono:Medium:13.0"   \
                                      \
    background.drawing=on             \
    background.padding_left=2         \
    background.padding_right=2        \
    background.color=0x6F5b6078       \
    background.corner_radius=3       \
    background.height=30              \
                                      \
    icon.drawing=on                   \
    icon.color=0xFF363a4f             \
    icon.highlight_color=0xFF363a4f   \
    icon.padding_left=10              \
    icon.padding_right=10             \
    icon.font="IosevkaTerm Nerd Font Mono:Medium:14.0"    \
                                      \
    icon.background.height=30         \
    icon.background.corner_radius=12  \
                                      \
    label.padding_left=12             \
    label.padding_right=12

##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

for sid in {1..10}; do
  sketchybar                              \
    --add space "space.$sid" left         \
    --set "space.$sid"                    \
        associated_space="$sid"           \
        icon.drawing=off                  \
        label.font="IosevkaTerm Nerd Font Mono:Bold:13.0"     \
        background.drawing=off            \
        label.color=0x6fa5adcb            \
        label.highlight_color=0xfff4dbd6  \
        label.padding_left=2              \
        label.padding_right=2             \
        label="󰇄"                         \
        script="$PLUGIN_DIR/space.sh"     \
        click_script="yabai -m space --focus $sid"
done

sketchybar --add bracket spaces '/space\..*/'

##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set

sketchybar                               \
  --add item front_app left              \
  --set front_app                        \
      icon.drawing=off                   \
      label.font="IosevkaTerm Nerd Font Mono:Bold:12.0"      \
      background.padding_left=4         \
      associated_display=active          \
      script="$PLUGIN_DIR/front_app.sh"  \
  --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

sketchybar                           \
  --default                          \
      icon.padding_right=0           \
                                     \
  --add item clock right             \
  --set clock                        \
      icon.drawing=off               \
      script="$PLUGIN_DIR/clock.sh"  \
      update_freq=29

sketchybar                                \
  --default update_freq=10                \
                                          \
  --add item wifi right                   \
  --set wifi                              \
      icon="󰖩"                            \
      icon.color=0xFF8aadf4               \
      update_freq=5                       \
      script="$PLUGIN_DIR/wifi.sh"        \
                                          \
  --add slider volume right 100           \
  --set volume                            \
      slider.highlight_color=0xFFeed49f   \
      slider.background.height=8          \
      slider.background.corner_radius=4   \
      slider.background.color=0xff494d64  \
      slider.width=80                     \
      icon.color=0xFFeed49f               \
      icon.padding_right=12               \
      label.padding_right=0               \
      label.drawing=on                    \
      script="$PLUGIN_DIR/volume.sh"      \
  --subscribe volume volume_change        \
                                          \
  --add item battery right                \
  --set battery                           \
      icon="🔋"                            \
      icon.color=0xFFa6da95               \
      background.padding_left=0          \
      script="$PLUGIN_DIR/battery.sh"     \
  --subscribe battery system_woke

sketchybar                                       \
  --default                                      \
      update_freq=10                             \
      icon.drawing=off                           \
      label.drawing=off                          \
      background.drawing=off                     \
                                                 
  # --add alias "Control Center,FocusModes" right  \
  # --add alias "Amphetamine,Amphetamine"   right  \
  # --add alias "TickTick,Item-0"           right

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration and
# should never be run in an item script.

sketchybar --update

echo "sketchybar configuration loaded.."
